./out/tool ./cmd/tool/repo_add.sql golang/go https://github.com/golang/go master
./out/tool ./cmd/tool/repo_add.sql kubernetes/kubernetes https://github.com/kubernetes/kubernetes master
./out/tool ./cmd/tool/repo_add.sql fatedier/frp https://github.com/fatedier/frp dev
./out/tool ./cmd/tool/repo_add.sql gin-gonic/gin https://github.com/gin-gonic/gin master
./out/tool ./cmd/tool/repo_add.sql gohugoio/hugo https://github.com/gohugoio/hugo master
./out/tool ./cmd/tool/repo_add.sql moby/moby https://github.com/moby/moby master
./out/tool ./cmd/tool/repo_add.sql syncthing/syncthing https://github.com/syncthing/syncthing main
./out/tool ./cmd/tool/repo_add.sql junegunn/fzf https://github.com/junegunn/fzf master
./out/tool ./cmd/tool/repo_add.sql caddyserver/caddy https://github.com/caddyserver/caddy master
./out/tool ./cmd/tool/repo_add.sql prometheus/prometheus https://github.com/prometheus/prometheus main
./out/tool ./cmd/tool/repo_add.sql nektos/act https://github.com/nektos/act master
./out/tool ./cmd/tool/repo_add.sql traefik/traefik https://github.com/traefik/traefik master
./out/tool ./cmd/tool/repo_add.sql etcd-io/etcd https://github.com/etcd-io/etcd main
./out/tool ./cmd/tool/repo_add.sql ethereum/go-ethereum https://github.com/ethereum/go-ethereum master
./out/tool ./cmd/tool/repo_add.sql FiloSottile/mkcert https://github.com/FiloSottile/mkcert master
./out/tool ./cmd/tool/repo_add.sql v2ray/v2ray-core https://github.com/v2ray/v2ray-core master
./out/tool ./cmd/tool/repo_add.sql gogs/gogs https://github.com/gogs/gogs main
./out/tool ./cmd/tool/repo_add.sql minio/minio https://github.com/minio/minio master
./out/tool ./cmd/tool/repo_add.sql jesseduffield/lazygit https://github.com/jesseduffield/lazygit master
./out/tool ./cmd/tool/repo_add.sql astaxie/build-web-application-with-golang https://github.com/astaxie/build-web-application-with-golang master
./out/tool ./cmd/tool/repo_add.sql rclone/rclone https://github.com/rclone/rclone master
./out/tool ./cmd/tool/repo_add.sql wagoodman/dive https://github.com/wagoodman/dive main
./out/tool ./cmd/tool/repo_add.sql go-gitea/gitea https://github.com/go-gitea/gitea main
./out/tool ./cmd/tool/repo_add.sql hashicorp/terraform https://github.com/hashicorp/terraform main
./out/tool ./cmd/tool/repo_add.sql evanw/esbuild https://github.com/evanw/esbuild main
./out/tool ./cmd/tool/repo_add.sql ollama/ollama https://github.com/ollama/ollama main
./out/tool ./cmd/tool/repo_add.sql pingcap/tidb https://github.com/pingcap/tidb master
./out/tool ./cmd/tool/repo_add.sql spf13/cobra https://github.com/spf13/cobra main
./out/tool ./cmd/tool/repo_add.sql alist-org/alist https://github.com/alist-org/alist main
./out/tool ./cmd/tool/repo_add.sql go-gorm/gorm https://github.com/go-gorm/gorm master
./out/tool ./cmd/tool/repo_add.sql cli/cli https://github.com/cli/cli trunk
./out/tool ./cmd/tool/repo_add.sql istio/istio https://github.com/istio/istio master
./out/tool ./cmd/tool/repo_add.sql unknwon/the-way-to-go_ZH_CN https://github.com/unknwon/the-way-to-go_ZH_CN master
./out/tool ./cmd/tool/repo_add.sql coreybutler/nvm-windows https://github.com/coreybutler/nvm-windows master
./out/tool ./cmd/tool/repo_add.sql jesseduffield/lazydocker https://github.com/jesseduffield/lazydocker master
./out/tool ./cmd/tool/repo_add.sql docker/compose https://github.com/docker/compose main
./out/tool ./cmd/tool/repo_add.sql pocketbase/pocketbase https://github.com/pocketbase/pocketbase master
./out/tool ./cmd/tool/repo_add.sql photoprism/photoprism https://github.com/photoprism/photoprism develop
./out/tool ./cmd/tool/repo_add.sql halfrost/LeetCode-Go https://github.com/halfrost/LeetCode-Go master
./out/tool ./cmd/tool/repo_add.sql harness/gitness https://github.com/harness/gitness main
./out/tool ./cmd/tool/repo_add.sql beego/beego https://github.com/beego/beego master
./out/tool ./cmd/tool/repo_add.sql gofiber/fiber https://github.com/gofiber/fiber main
./out/tool ./cmd/tool/repo_add.sql hashicorp/vault https://github.com/hashicorp/vault main
./out/tool ./cmd/tool/repo_add.sql cockroachdb/cockroach https://github.com/cockroachdb/cockroach master
./out/tool ./cmd/tool/repo_add.sql ehang-io/nps https://github.com/ehang-io/nps master
./out/tool ./cmd/tool/repo_add.sql kubernetes/minikube https://github.com/kubernetes/minikube master
./out/tool ./cmd/tool/repo_add.sql labstack/echo https://github.com/labstack/echo master
./out/tool ./cmd/tool/repo_add.sql hashicorp/consul https://github.com/hashicorp/consul main
./out/tool ./cmd/tool/repo_add.sql zeromicro/go-zero https://github.com/zeromicro/go-zero master
./out/tool ./cmd/tool/repo_add.sql v2fly/v2ray-core https://github.com/v2fly/v2ray-core master
./out/tool ./cmd/tool/repo_add.sql go-kit/kit https://github.com/go-kit/kit master
./out/tool ./cmd/tool/repo_add.sql k3s-io/k3s https://github.com/k3s-io/k3s master
./out/tool ./cmd/tool/repo_add.sql schollz/croc https://github.com/schollz/croc main
./out/tool ./cmd/tool/repo_add.sql helm/helm https://github.com/helm/helm main
./out/tool ./cmd/tool/repo_add.sql milvus-io/milvus https://github.com/milvus-io/milvus master
./out/tool ./cmd/tool/repo_add.sql spf13/viper https://github.com/spf13/viper master
./out/tool ./cmd/tool/repo_add.sql kataras/iris https://github.com/kataras/iris main
./out/tool ./cmd/tool/repo_add.sql usememos/memos https://github.com/usememos/memos main
./out/tool ./cmd/tool/repo_add.sql nsqio/nsq https://github.com/nsqio/nsq master
./out/tool ./cmd/tool/repo_add.sql openfaas/faas https://github.com/openfaas/faas master
./out/tool ./cmd/tool/repo_add.sql derailed/k9s https://github.com/derailed/k9s master
./out/tool ./cmd/tool/repo_add.sql yeasy/docker_practice https://github.com/yeasy/docker_practice master
./out/tool ./cmd/tool/repo_add.sql sirupsen/logrus https://github.com/sirupsen/logrus master
./out/tool ./cmd/tool/repo_add.sql Wox-launcher/Wox https://github.com/Wox-launcher/Wox v2
./out/tool ./cmd/tool/repo_add.sql inconshreveable/ngrok https://github.com/inconshreveable/ngrok master
./out/tool ./cmd/tool/repo_add.sql tmrts/go-patterns https://github.com/tmrts/go-patterns master
./out/tool ./cmd/tool/repo_add.sql zyedidia/micro https://github.com/zyedidia/micro master
./out/tool ./cmd/tool/repo_add.sql iawia002/lux https://github.com/iawia002/lux master
./out/tool ./cmd/tool/repo_add.sql dapr/dapr https://github.com/dapr/dapr master
./out/tool ./cmd/tool/repo_add.sql restic/restic https://github.com/restic/restic master
./out/tool ./cmd/tool/repo_add.sql grafana/k6 https://github.com/grafana/k6 master
./out/tool ./cmd/tool/repo_add.sql mislav/hub https://github.com/mislav/hub master
./out/tool ./cmd/tool/repo_add.sql filebrowser/filebrowser https://github.com/filebrowser/filebrowser master
./out/tool ./cmd/tool/repo_add.sql fyne-io/fyne https://github.com/fyne-io/fyne master
./out/tool ./cmd/tool/repo_add.sql charmbracelet/bubbletea https://github.com/charmbracelet/bubbletea master
./out/tool ./cmd/tool/repo_add.sql tsenart/vegeta https://github.com/tsenart/vegeta master
./out/tool ./cmd/tool/repo_add.sql go-kratos/kratos https://github.com/go-kratos/kratos main
./out/tool ./cmd/tool/repo_add.sql goharbor/harbor https://github.com/goharbor/harbor main
./out/tool ./cmd/tool/repo_add.sql go-delve/delve https://github.com/go-delve/delve master
./out/tool ./cmd/tool/repo_add.sql gocolly/colly https://github.com/gocolly/colly master
./out/tool ./cmd/tool/repo_add.sql stretchr/testify https://github.com/stretchr/testify master
./out/tool ./cmd/tool/repo_add.sql urfave/cli https://github.com/urfave/cli main
./out/tool ./cmd/tool/repo_add.sql grafana/loki https://github.com/grafana/loki main
./out/tool ./cmd/tool/repo_add.sql go-micro/go-micro https://github.com/go-micro/go-micro master
./out/tool ./cmd/tool/repo_add.sql AdguardTeam/AdGuardHome https://github.com/AdguardTeam/AdGuardHome master
./out/tool ./cmd/tool/repo_add.sql wailsapp/wails https://github.com/wailsapp/wails master
./out/tool ./cmd/tool/repo_add.sql quii/learn-go-with-tests https://github.com/quii/learn-go-with-tests main
./out/tool ./cmd/tool/repo_add.sql containers/podman https://github.com/containers/podman main
./out/tool ./cmd/tool/repo_add.sql gorilla/websocket https://github.com/gorilla/websocket main
./out/tool ./cmd/tool/repo_add.sql valyala/fasthttp https://github.com/valyala/fasthttp master
./out/tool ./cmd/tool/repo_add.sql XTLS/Xray-core https://github.com/XTLS/Xray-core main
./out/tool ./cmd/tool/repo_add.sql uber-go/zap https://github.com/uber-go/zap master
./out/tool ./cmd/tool/repo_add.sql aquasecurity/trivy https://github.com/aquasecurity/trivy main
./out/tool ./cmd/tool/repo_add.sql seaweedfs/seaweedfs https://github.com/seaweedfs/seaweedfs master
./out/tool ./cmd/tool/repo_add.sql cloudreve/Cloudreve https://github.com/cloudreve/Cloudreve master
./out/tool ./cmd/tool/repo_add.sql IceWhaleTech/CasaOS https://github.com/IceWhaleTech/CasaOS main
./out/tool ./cmd/tool/repo_add.sql dgraph-io/dgraph https://github.com/dgraph-io/dgraph main
./out/tool ./cmd/tool/repo_add.sql gorilla/mux https://github.com/gorilla/mux main
