// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: lint_highlights_queries.sql

package storage

import (
	"context"
)

const addLintHighlight = `-- name: AddLintHighlight :exec
INSERT INTO lint_highlights (lint_id, path, start_line, end_line, explanation, snippet_start_line, snippet_end_line, snippet_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddLintHighlightParams struct {
	LintID           string
	Path             string
	StartLine        int32
	EndLine          int32
	Explanation      string
	SnippetStartLine int32
	SnippetEndLine   int32
	SnippetCode      string
}

func (q *Queries) AddLintHighlight(ctx context.Context, arg AddLintHighlightParams) error {
	_, err := q.db.Exec(ctx, addLintHighlight,
		arg.LintID,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.Explanation,
		arg.SnippetStartLine,
		arg.SnippetEndLine,
		arg.SnippetCode,
	)
	return err
}
